### PR TITLE
Added scan, sscan, hscan, zscan basic operations

### PR DESCRIPTION
**Pull request by ggl**

### CODE REVIEW

**Comment by jhthorsen** [comment]
Thanks for the PR, but I can't merge until travis stops complaining:

https://travis-ci.org/jhthorsen/mojo-redis2/jobs/61012377
https://travis-ci.org/jhthorsen/mojo-redis2/jobs/61012380

Let me know if you have any theory on what's wrong.

**Comment by ggl** [comment]
I'll have to install 5.20.2 and 5.10.1 locally to figgure it out.

**Comment by ggl** [comment]
Can you rerun the tests? Travis failed this time due to a network error.

**Comment by jhthorsen** [comment]
Seems to be failing https://travis-ci.org/jhthorsen/mojo-redis2/jobs/61313653

```
#   Failed test 'scan'
#   at t/all-basic-operations.t line 72.
#     Structures begin differing at:
#          $got->[0] = Does not exist
#     $expected->[0] = 'redis2:test:Keys'
```

Not sure why this only happens on 5.20.0.

**Comment by ggl** [comment]
The perl version is not important. It's due to the way scan works. You could get back the matched keys or you could get back nothing. I modified the test a bit to do several iterations util the cursor is back to 0 (usually only takes one) and increased the count to 100.

**Comment by jhthorsen** [comment]
I'm a bit unsure now, if these methods fits in the default package. I think maybe we should have Mojo::Redis2::Scan with the methods you have created here, but also methods like keys, hkeys, smembers and zmembers which use scan, hscan, sscan and zscan to generate the result.

What do you think?

**Comment by ggl** [comment]
I think it only makes sense to put the *scan functions in a different package if you take care of the cursor loops transparently, i.e. do several iterations and get all the keys using *scan when the user does something like:

    @keys = $redis->scan->keys;

**Comment by jhthorsen** [comment]
Yes, that was the idea. Fixing all the uniqueness "issues" and such in Perl space.

**Comment by jhthorsen** [comment]
Closing this since #18 is merged.

**Pull request closed without merging**
